### ISSUE TITLE
launcher.py not working in Linux

### ISSUE THREAD

**Issue by manuelmoncada** [ansys/pyrocky#55]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I try to open Rocky from Python with pyrocky.launch_rocky(), it cannot find the Rocky binary file, because the AWP_ROOT  enviaroment variable is not defined by default in the installation

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pyrocky/lib/python3.11/site-packages/ansys/rocky/core/launcher.py", line 78, in launch_rocky
    raise FileNotFoundError("Rocky executable is not found.")
FileNotFoundError: Rocky executable is not found.

### 📝 Steps to reproduce

- Install ansys-rocky-core
- run the following script:

import ansys.rocky.core as pyrocky
rocky = pyrocky.launch_rocky()

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

Ansys Rocky 2024 R1.1

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
ansys-rocky-core==0.1.0
importlib_metadata==7.1.0
numpy==1.26.4
Pyro5==5.15
serpent==1.41
zipp==3.18.1
```

**Comment by igortg** [comment]
Hi @manuelmoncada 

Sorry that we took so long to respond. The workaround right now is to manually set `rocky_exe` parameter for `launch_rocky`.

    rocky = pyrocky.launch_rocky(rocky_exe='/ansys_inc/v241/rocky/bin/Rocky')

**Comment by igortg** [comment]
This was probably fixed by #143
